name: After_Market_Scan

on:
  schedule:
    - cron: '30 7 * * 1-5' # 台北時間週一至週五 15:30 執行
  workflow_dispatch:      # 手動測試按鈕

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas requests FinMind tqdm lxml

      - name: Run Market Scan
        run: python myscreen.py
        env:
          TZ: "Asia/Taipei"

      - name: Commit and Push targets.txt
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add targets.txt
          git commit -m "Update target list" || echo "No changes"
          git push
