name: Stock_Scanner_Final

on:
  schedule:
    # 台北時間週一至週五 15:30 執行 (UTC 07:30)
    - cron: '30 7 * * 1-5' 
  workflow_dispatch: # 讓你可以點擊按鈕手動測試

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests FinMind tqdm lxml
      
      - name: Run Scan
        run: python myscreen.py
        env:
          TZ: "Asia/Taipei"
